# WARNING: this source code was automatically generated by pyFUME.
from simpful import *

FS = FuzzySystem(show_banner=False)
RULE1 = "IF (sex_male IS cluster1) AND (smoker_yes IS cluster1) AND (region_northwest IS cluster1) AND (region_southeast IS cluster1) AND (region_southwest IS cluster1) AND (age IS cluster1) AND (bmi IS cluster1) AND (children IS cluster1) THEN (OUTPUT IS fun1)"
RULE2 = "IF (sex_male IS cluster2) AND (smoker_yes IS cluster2) AND (region_northwest IS cluster2) AND (region_southeast IS cluster2) AND (region_southwest IS cluster2) AND (age IS cluster2) AND (bmi IS cluster2) AND (children IS cluster2) THEN (OUTPUT IS fun2)"
RULE3 = "IF (sex_male IS cluster3) AND (smoker_yes IS cluster3) AND (region_northwest IS cluster3) AND (region_southeast IS cluster3) AND (region_southwest IS cluster3) AND (age IS cluster3) AND (bmi IS cluster3) AND (children IS cluster3) THEN (OUTPUT IS fun3)"
FS.add_rules([RULE1, RULE2, RULE3])

FS.set_output_function('fun1', '-2.216731e+02*sex_male+2.505197e+04*smoker_yes+-5.730731e+02*region_northwest+-1.203252e+03*region_southeast+-1.215972e+03*region_southwest+2.720138e+02*age+3.478885e+02*bmi+4.510895e+02*children+-1.269124e+04')
FS.set_output_function('fun2', '-2.763240e+02*sex_male+2.368050e+04*smoker_yes+-5.444739e+02*region_northwest+-1.200249e+03*region_southeast+-1.478803e+03*region_southwest+2.634533e+02*age+1.189387e+02*bmi+4.938468e+02*children+-5.169940e+03')
FS.set_output_function('fun3', '-1.235007e+02*sex_male+2.331994e+04*smoker_yes+-5.438752e+02*region_northwest+-1.087591e+03*region_southeast+-1.105094e+03*region_southwest+2.693851e+02*age+3.558393e+02*bmi+4.186869e+02*children+-1.257085e+04')

FS_1 = FuzzySet(function=Gaussian_MF(0.501663, 3.303774), term='cluster1')
FS_2 = FuzzySet(function=Gaussian_MF(0.400951, 5.652216), term='cluster2')
FS_3 = FuzzySet(function=Gaussian_MF(0.537545, 3.712056), term='cluster3')
MF_sex_male = LinguisticVariable([FS_1, FS_2, FS_3], concept='sex_male' , universe_of_discourse=(0.0, 1.0))
FS.add_linguistic_variable('sex_male', MF_sex_male)

FS_4 = FuzzySet(function=Gaussian_MF(1.213220, 4.164795), term='cluster1')
FS_5 = FuzzySet(function=Gaussian_MF(-0.175178, 0.636618), term='cluster2')
FS_6 = FuzzySet(function=Gaussian_MF(0.434901, 4.114423), term='cluster3')
MF_smoker_yes = LinguisticVariable([FS_4, FS_5, FS_6], concept='smoker_yes' , universe_of_discourse=(0.0, 1.0))
FS.add_linguistic_variable('smoker_yes', MF_smoker_yes)

FS_7 = FuzzySet(function=Gaussian_MF(0.514813, 3.402177), term='cluster1')
FS_8 = FuzzySet(function=Gaussian_MF(0.393920, 4.652963), term='cluster2')
FS_9 = FuzzySet(function=Gaussian_MF(0.567390, 3.237773), term='cluster3')
MF_region_northwest = LinguisticVariable([FS_7, FS_8, FS_9], concept='region_northwest' , universe_of_discourse=(0.0, 1.0))
FS.add_linguistic_variable('region_northwest', MF_region_northwest)

FS_10 = FuzzySet(function=Gaussian_MF(0.590529, 4.155954), term='cluster1')
FS_11 = FuzzySet(function=Gaussian_MF(0.403297, 4.426193), term='cluster2')
FS_12 = FuzzySet(function=Gaussian_MF(0.518263, 2.769884), term='cluster3')
MF_region_southeast = LinguisticVariable([FS_10, FS_11, FS_12], concept='region_southeast' , universe_of_discourse=(0.0, 1.0))
FS.add_linguistic_variable('region_southeast', MF_region_southeast)

FS_13 = FuzzySet(function=Gaussian_MF(0.463546, 2.829639), term='cluster1')
FS_14 = FuzzySet(function=Gaussian_MF(0.518592, 3.641636), term='cluster2')
FS_15 = FuzzySet(function=Gaussian_MF(0.443543, 5.406242), term='cluster3')
MF_region_southwest = LinguisticVariable([FS_13, FS_14, FS_15], concept='region_southwest' , universe_of_discourse=(0.0, 1.0))
FS.add_linguistic_variable('region_southwest', MF_region_southwest)

FS_16 = FuzzySet(function=Gaussian_MF(34.473211, 92.388700), term='cluster1')
FS_17 = FuzzySet(function=Gaussian_MF(31.519216, 21.351161), term='cluster2')
FS_18 = FuzzySet(function=Gaussian_MF(41.685486, 386.339567), term='cluster3')
MF_age = LinguisticVariable([FS_16, FS_17, FS_18], concept='age' , universe_of_discourse=(18.0, 64.0))
FS.add_linguistic_variable('age', MF_age)

FS_19 = FuzzySet(function=Gaussian_MF(40.461835, 16.337560), term='cluster1')
FS_20 = FuzzySet(function=Gaussian_MF(29.553530, 32.626087), term='cluster2')
FS_21 = FuzzySet(function=Gaussian_MF(30.116242, 16.342542), term='cluster3')
MF_bmi = LinguisticVariable([FS_19, FS_20, FS_21], concept='bmi' , universe_of_discourse=(15.96, 52.58))
FS.add_linguistic_variable('bmi', MF_bmi)

FS_22 = FuzzySet(function=Gaussian_MF(1.689542, 2.900527), term='cluster1')
FS_23 = FuzzySet(function=Gaussian_MF(2.500000, 43.305492), term='cluster2')
FS_24 = FuzzySet(function=Gaussian_MF(1.461951, 10.183097), term='cluster3')
MF_children = LinguisticVariable([FS_22, FS_23, FS_24], concept='children' , universe_of_discourse=(0.0, 5.0))
FS.add_linguistic_variable('children', MF_children)


# end of automatically generated code #